### ISSUE TITLE
Need to fill in contact information on beta.uipa.org

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/uipa_org#1]
As a person making an FOI request, I want to be able to select the contact/department of where I'm making my FOI request. 

Please use Sara's documents: 
- https://docs.google.com/spreadsheets/d/13kI1lo_wD2buawcnrDbxRv-mowSwAORuoFeTKyU78Us/edit#gid=1787992467
- https://docs.google.com/spreadsheets/d/1bla9HwEdafS2enAoJeUomI3jJ-jLKQs-DRmEW3Lsy3I/edit#gid=1787992467
- https://docs.google.com/spreadsheets/d/14y3uJDYizsSgxlfsJhIs6ZfKx3gjXexXnQms3QdhrWg/edit#gid=1787992467

Please don't use real email addresses on beta

**Comment by sakamosa** [comment]
Real email addresses can be used with the Email Dry Run configuration:
http://froide.readthedocs.org/en/latest/configuration/

**Comment by ryankanno** [comment]
Will make a new task encompassing both beta/prod.
