### ISSUE TITLE
Add google analytics to beta.uipa.org

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/uipa_org#15]
As a uipa maintainer, I want to collect metrics about how users are getting to the product and how they are using the product to be able to optimize their experience

**Comment by jonifatu** [comment]
Does codeforhawaii have a google analytics account?

**Comment by ryankanno** [comment]
@jonifatu We do! I'll generate the snippet that needs to be added and attach it to this issue!

**Comment by ryankanno** [comment]
Need to add the following into the templates:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62408196-2', 'auto');
  ga('send', 'pageview');
</script>
```
