### ISSUE TITLE
Create help page

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/uipa_org#22]
As a uipa user, I want to seek out a help page to find more information on how to use the system.

This should be done in the uipa admin, then scripted out. Point the flatpage to help/page.html. See [Flatpages docs](https://docs.djangoproject.com/en/1.8/ref/contrib/flatpages/) and this [commit](https://github.com/CodeforHawaii/froide/commit/ec8aaa18bdae9c788b87fdd2c47ddd78e77698e2) for more information.

Acceptance:
Help page should contain:
- Link to the UIPA law
- Instructions (or screenshots) on how to use the system

**Comment by ryankanno** [comment]
See #21 as well.

**Comment by russtoku** [comment]
Does Issue #30 cover the part about creating a page in the uipa admin, scripting it out, pointing the flat page to the help/page.html, etc.?

**Comment by ryankanno** [comment]
This has been completed by BB.
