### ISSUE TITLE
Create about page

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/uipa_org#23]
As a uipa user, I want to seek out an about page to find more information on the background of the system.

This should be done in the uipa admin, then scripted out. Point the flatpage to help/page.html. See [Flatpages docs](https://docs.djangoproject.com/en/1.8/ref/contrib/flatpages/) and this [commit](https://github.com/CodeforHawaii/froide/commit/ec8aaa18bdae9c788b87fdd2c47ddd78e77698e2) for more information.

Acceptance:

About page should contain:
- Link to history of UIPA law
- People who have made this possible

**Comment by russtoku** [comment]
Which people made UIPA.org possible? Or UIPA possible?

**Comment by russtoku** [comment]
See pull request associated with #36

**Comment by ryankanno** [comment]
Going to close this one for now. Will create a new ticket to move the file from its current place into a fixtures folder.
